# Generated by Django 5.0.7 on 2024-07-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
